title = "ASPLOS'22 Tutorial"
baseURL = "/"
languageCode = "en-us"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Learn more about Unikraft"
    url = "https://unikraft.org"
    weight = 2

[params]

  [params.homepage_meta_tags]
    meta_description = "Unikraft ASPLOS'22 Tutorial"
    meta_og_title = "Unikraft ASPLOS'22 Tutorial"
    meta_og_type = "website"
    meta_og_url = "https://asplos22.unikraft.org"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@UnikraftSDK"
    meta_twitter_creator = "@UnikraftSDK"

  [params.logo]
      mobile = "/images/unikraft.svg"
      standard  = "/images/unikraft.svg"
